###测试申请令牌  授权码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=NL306W&redirect_uri=http://www.51xuecheng.cn

### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"stu1","authType":"password","password":"111111"}

###通过check_token接口校验jwt令牌
POST {{auth_host}}/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMi0wOS0yOFQxOToyODo0NlwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMi0wOS0yOFQwODozMjowM1wiLFwiaWRcIjpcIjUwXCIsXCJuYW1lXCI6XCLlrabnlJ8xXCIsXCJuaWNrbmFtZVwiOlwi5aSn5rC054mbXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcInN0dTFcIixcInVzZXJwaWNcIjpcImh0dHA6Ly9maWxlLnh1ZWNoZW5nLXBsdXMuY29tL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjk4MjI3MzAyLCJhdXRob3JpdGllcyI6WyJ0ZXN0Il0sImp0aSI6IjY3OGVkYTg3LWE1YTEtNDQyMi05ZTIzLWJiN2E0ZjBlY2U5MiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.kR1nUbZna0YKiVWgLoVP2mlz2vI3g4rlPEtPlrojdMs

###通过网关校验jwt令牌访问资源服务
GET http://localhost:60010/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTgwMzAyNDQsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImVmMzZlNGNiLThmNWEtNGE3Mi04OGQzLWFlMmM4MGQwYjcxYiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.nOXvnh9wSUXie5UOds5EqqdbIrqG_RvHMMY4EP48jzg
