### 课程查询列表
###用idea中的HTTPClient委托发送请求 测试接口  放在一个单独的地方存放 以便于保存
### 将需要的主机ip放在json环境变量文件中，用{{}}引入 方便后续操作
POST {{content_host}}/content/course/list?pageNo=2&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}
###Get请求测试 课程分类查询树形结点数据
GET {{content_host}}/content/course-category/tree-nodes

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "",
  "st": "",
  "name": "",
  "pic": "",
  "teachmode": "",
  "users": "初",
  "tags": "",
  "grade": "",
  "description": ""
}

###查询课程信息
GET {{content_host}}/content/course/40

###修改课程信息 包括课程基本信息、课程营销信息
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id" : "1",
  "charge": "201001",
  "price": 20,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "java",
  "pic": "",
  "teachmode": "",
  "users": "初学者1111111111",
  "tags": "",
  "grade": "204002",
  "description": ""
}

###查询课程计划
GET {{content_host}}/content/teachplan/74/tree-nodes

### 课程查询列表
POST {{gateway_host}}/content/course/list?pageNo=2&pageSize=1
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}




