### 新增课程计划--章
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 0,
  "grade" : 1,
  "pname" : "新章名称 1"
}

###
DELETE {{content_host}}/content/teachplan/294

###
DELETE {{content_host}}/content/course/130

###
DELETE {{media_host}}/media/teachplan/association/media/282/1f229319d6fed3431d2f9d06193a433b
